/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CronScheduler: typeof import('./src/components/repeatables/CronScheduler.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Divider: typeof import('primevue/divider')['default']
    EditableText: typeof import('./src/components/editable/EditableText.vue')['default']
    EmptyTasks: typeof import('./src/components/empty/EmptyTasks.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HStack: typeof import('./src/components/stack/HStack.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Listbox: typeof import('primevue/listbox')['default']
    ManagementPresentation: typeof import('./src/components/management/ManagementPresentation.vue')['default']
    ManagementSchedule: typeof import('./src/components/management/ManagementSchedule.vue')['default']
    MeterGroup: typeof import('primevue/metergroup')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Tag: typeof import('primevue/tag')['default']
    TagsInput: typeof import('./src/components/editable/TagsInput.vue')['default']
    TaskAdd: typeof import('./src/components/task/TaskAdd.vue')['default']
    TaskControl: typeof import('./src/components/TaskControl.vue')['default']
    TaskGroup: typeof import('./src/components/task/TaskGroup.vue')['default']
    TaskHeader: typeof import('./src/components/task/TaskHeader.vue')['default']
    TaskList: typeof import('./src/components/task/TaskList.vue')['default']
    TaskManagement: typeof import('./src/components/TaskManagement.vue')['default']
    TaskPresentation: typeof import('./src/components/task/TaskPresentation.vue')['default']
    TaskSearch: typeof import('./src/components/task/TaskSearch.vue')['default']
    TaskToolbar: typeof import('./src/components/task/TaskToolbar.vue')['default']
    VStack: typeof import('./src/components/stack/VStack.vue')['default']
  }
  export interface ComponentCustomProperties {
    FocusTrap: typeof import('primevue/focustrap')['default']
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
