/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Editable: typeof import('./src/components/editable/Editable.vue')['default']
    EditableText: typeof import('./src/components/editable/EditableText.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Listbox: typeof import('primevue/listbox')['default']
    ManagementPresentation: typeof import('./src/components/management/ManagementPresentation.vue')['default']
    ManagementSchedule: typeof import('./src/components/management/ManagementSchedule.vue')['default']
    MeterGroup: typeof import('primevue/metergroup')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    Panel: typeof import('primevue/panel')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Splitter: typeof import('primevue/splitter')['default']
    SplitterPanel: typeof import('primevue/splitterpanel')['default']
    Tag: typeof import('primevue/tag')['default']
    TagsInput: typeof import('./src/components/editable/TagsInput.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TheTodo: typeof import('./src/components/TheTodo.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TodoAdd: typeof import('./src/components/todo/TodoAdd.vue')['default']
    TodoControl: typeof import('./src/components/TodoControl.vue')['default']
    TodoForm: typeof import('./src/components/todo/TodoForm.vue')['default']
    TodoGroup: typeof import('./src/components/todo/TodoGroup.vue')['default']
    TodoHeader: typeof import('./src/components/todo/TodoHeader.vue')['default']
    TodoItem: typeof import('./src/components/todo/TodoItem.vue')['default']
    TodoList: typeof import('./src/components/todo/TodoList.vue')['default']
    TodoManagement: typeof import('./src/components/TodoManagement.vue')['default']
    TodoPresentation: typeof import('./src/components/todo/TodoPresentation.vue')['default']
    TodoSearch: typeof import('./src/components/todo/TodoSearch.vue')['default']
    TodoToolbar: typeof import('./src/components/todo/TodoToolbar.vue')['default']
    TodoToolBar: typeof import('./src/components/todo/TodoToolBar.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    FocusTrap: typeof import('primevue/focustrap')['default']
    Ripple: typeof import('primevue/ripple')['default']
  }
}
