[package]
name = "scheduler"
version = "0.1.0"
authors = ["Caleb Adepitan <hello@calebpitan.com>"]
edition = "2018"
repository = "https://github.com/calebpitan/stitches"
license = "MIT OR Apache-2.0"
description = "A scheduler program for tracking schedules and dispatching timely events"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.84"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }
cron-parser = "0.9.0"
chrono = "0.4.38"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Window", "AbortController", "AbortSignal"] }
async-std = "1.13.0"
serde = { version = "1.0.210", features = ["derive"] }
wasm-bindgen-futures = "0.4.45"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
